import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Kooler",
  description: "Generated by Kooler",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-[90%] h-[90%] m-auto `}>{children}</body>
    </html>
  );
}
